version: 0.0
os: linux

files:
  - source: /build
    destination: /home/ubuntu/deploy-fe
    overwrite: yes

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/deploy-fe
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root